### ISSUE TITLE
Закрытие сокета после отправки.

### ISSUE THREAD

**Issue by BaxterZA** [vladon/SocketNative#1]
Подскажите зачем вы закрываете сокет после отправки?
https://github.com/vladon/SocketNative/blob/master/uSocketNative.pas#L479

Для чего тогда команда Отключиться?

**Comment by vladon** [comment]
А хз :) Можете исправить :)

**Comment by BaxterZA** [comment]
Да, сделал для себя без закрытия. Спасибо, очень удобная либа.
